blog/urls.py
from django.urls import path
from .views import (
 ArticleList,
 ArticleDetail,
 Articlepreview,
 CategoryList,
 AuthorList,
 SearchList,
)

app_name = "blog"
urlpatterns = [
        path('', ArticleList.as_view(), name="home"),
        path('page/<int:page>', ArticleList.as_view(), name="home"),
        path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
        path('preview/<int:pk>', Articlepreview.as_view(), name="preview"),
        path('category/<slug:slug>', CategoryList.as_view(), name="category"),
        path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
        path('author/<slug:username>', AuthorList.as_view(), name="author"),
        path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
        path('search/', SearchList.as_view(), name="search"),
        path('search/page/<int:page>', SearchList.as_view(), name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from account.models import User 
from django.utils.html import format_html
from django.utils import timezone
from extensions.utils import jalali_converter


# Article Manager based on articles that are published.
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

# Category Manager based on categories that are active.
class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)



class IPAddress(models.Model):
    """This model shows the IP addresses of users."""

    ip_address = models.GenericIPAddressField(verbose_name="آدرس آی پی")

    class Meta:
        verbose_name = "آدرس آی پی"
        verbose_name_plural = "آدرس آی پی ها"

        
class Category(models.Model):
    """
    This model is related to the classification of articles, which can 
    create article categories and subcategories for each article.
    """

    parent=models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title=models.CharField(max_length=200, verbose_name='دسته بندی عناوین')
    slug=models.SlugField(max_length=100, unique=True,verbose_name='آدرس دسته بندی')
    status=models.BooleanField(default=True,verbose_name='آیا نمایش داده شوند؟')
    position=models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering=['parent__id','position']

    def __str__(self):
        return self.title

    objects = CategoryManager()

class Article(models.Model):
    """This model is related to user articles."""
    
    STATUS_CHOICES=(
        ('d', 'پیش نویس'),        # draft
        ('p', 'منتشرشده'),        # publish
        ('i', 'در حال بررسی'),    # investigation
        ('b', 'برگشت داده شده'),   # back

    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name="نویسنده")
    title=models.CharField(max_length=200, verbose_name='عنوان مقاله')
    slug=models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')
    category=models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
    description=models.TextField(verbose_name='محتوا')
    thumbnail=models.ImageField(upload_to="images", verbose_name='تصویر مقاله')
    publish=models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    is_special=models.BooleanField(default=False,verbose_name='مقاله ویژه')
    status=models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='وضعیت')
    hits = models.ManyToManyField(IPAddress, through= "ArticleHit", blank=True, related_name="hits", verbose_name="بازدیدها")
    
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقاله ها"
        ordering=['-publish']

    def __str__(self):
        return self.title
    

    def get_absolute_url(self):
        return reverse("account:home")
    

    def jpublish(self):
        """This method is for Persianizing the date and time."""

        return jalali_converter(self.publish)
    
    jpublish.short_description = "زمان انتشار"



    def thumbnail_tag(self):
        """
        This method also shows the photos of the articles in the admin 
        panel of Django in the articles section Community Verified icon.
        """

        return format_html("<img width=100 height=75 style = 'border-radius: 13px'; src='{}'>".format(self.thumbnail.url))    
    thumbnail_tag.short_description = "عکس مقاله"


    def category_to_str(self):
        """
        This method puts a comma in the category section where it shows 
        which category the articles belong to so that they can be seen better.
        """

        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description="دسته بندی"


    objects = ArticleManager()


class ArticleHit(models.Model):
    """
    This model is related to the number of views of articles, which 
    counts the number of articles according to the IP address of each user.
    """
    
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)

blog/views.py
from django.views.generic import ListView, DetailView
from account.models import User 
from account.mixins import AuthorAccessMixin
from django.shortcuts import get_object_or_404
from .models import Article, Category
from django.db.models import Count ,Q
from datetime import datetime, timedelta


class ArticleList(ListView):
    """
    This view shows the articles and pagination and the method 
    below shows the most visited articles in the last month.
    """

    queryset = Article.objects.published()
    paginate_by = 5

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       last_month =  datetime.today() - timedelta(days=30)
       context['popular_articles'] = Article.objects.published().annotate(
        count = Count('hits', filter=Q(articlehit__created__gt=last_month))
       ).order_by('-count', '-publish')[:1000]
       return context



class ArticleDetail(DetailView):
    """
    This view is related to the details page of the articles and it shows 
    the number of views of the articles according to the IP of each user.
    """

    def get_object(self):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug=slug)

        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)
        return article



class Articlepreview(AuthorAccessMixin,DetailView):
    """
    This view is related to the time when a user's article is in draft status and has not been 
    published yet, so a normal user can see the preview of article through her admin panel.
    """

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)



class CategoryList(ListView):
    """This view is related to the pagination of article categories."""

    paginate_by = 5
    template_name = 'blog/category_list.html'
    
    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()
    
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['category'] = category
       return context



class AuthorList(ListView):
    """This view is related to the pagination of each user's articles separately."""

    paginate_by = 5
    template_name = 'blog/author_list.html'
    
    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()
    
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['author'] = author
       return context



class SearchList(ListView):
    """This view is related to the pagination of search results."""
    
    paginate_by = 5
    template_name = 'blog/search_list.html'
    
    def get_queryset(self):
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))
    
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['search'] = self.request.GET.get('q')
       return context

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load base_tags %}
{% block title %} | {{object.title}}{% endblock %}
{% block main %}
<!-- Page Header-->
 <header class="masthead" style="background-image: url('{{article.thumbnail.url}}');padding-top: 15.5rem;padding-bottom: 5.5rem">
     <div class="container position-relative px-4 px-lg-5">
         <div class="row gx-4 gx-lg-5 justify-content-center">
             <div class="col-md-10 col-lg-8 col-xl-7">
                 <div class="site-heading">
                     <h1 style="font-size: 2.1rem">{{object.title}}</h1>
                     <time>{{object.jpublish}}</time>
                     <div> بازدیدها:{{object.hits.count}}</div>   
                      {% if article.is_special %} 
                        <span class="badge bg-danger"style="font-size:16px">ویژه</span>
                      {% endif %}
                     <span class="subheading"></span>
                 </div>
             </div>
         </div>
     </div>
 </header>

    <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                      {% if object.is_special %}
                        {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                          {{object.description | safe}}
                        {% else %}
                            {{article.description | striptags | truncatewords:20}}
                          <p class="vizhe alert alert-warning">این مقاله ویژه است و برای مشاهده ی آن باید به ادمین های سایت خبر دهید بر روی<a class="alert-link" href="{% url 'blog:home' %}"> بازگشت </a> کلیک کنید </p>
                        {% endif %}
                      {% else %}
                       {{object.description | safe}}
                      {% endif %}
                    </div>
                </div>
            </div>
        </article>
{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}
  <div class="popular_articles alert alert-primary" style="font-family: Sahel-Bold">
    <h3 style="font-family: Sahel-Bold;">آرشیو مقاله ها</h3>
        <details>
          <summary>کلیک کنید</summary>
          {% for a in popular_articles %}
            <div><a href="{% url 'blog:detail' a.slug %}" style="color:#022964"> {{a.title}} </div></a>
          {% endfor %}
        </details>
  </div>
{% endblock %}

{% block previous_page_url %}
  {% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
  {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center" style="font-family:Sahel-Bold;width:100%;margin-right:2px;">نویسنده:{{author.get_full_name}}</h3>
{% endblock %}

{% block previous_page_url %}
   {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
   {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>وبلاگ جنگویی{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="{% static 'blog/https://use.fontawesome.com/releases/v6.1.0/js/all.js' %}" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="{% static 'blog/https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'blog/https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' %}" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/bootstrap-rtl.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body data-target=".navbar" data-offset="50" position="relative">
        <!-- Navigation-->
        <nav class="n navbar navbar-expand-md navbar-light">
          <button style="margin-bottom:50px" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            {% category_navbar %}
              <form class="form-inline mt-3" style="margin-left:33px;" action="{% url 'blog:search' %}"> 
                <input type="search" id="query" style="border-radius:8px; font-family: Sahel-Bold;" class="form-control" name="q" placeholder="جستجو...">
                <button class="btn btn-success" style="padding: 8px; border-radius: 5px; margin-top: 3px; font-family: Sahel-Bold;">پیدا کن</button>
              </form>
        </nav>
        
       {% block main %}
       {% endblock %}
        <!-- Footer-->
        <footer class="Jumbotron Jumbotron-fluid">
          <div class="container footer mt-4">
            <div class="card border-0 mt-5 p-3">
                <h2 style="text-align: center; font-family: Sahel-Bold; ">ارتباط با ما</h2>
                <div class="card-body p-5">
                  <div class="row text-center">
                    <div class="col-4">
                        <i class="fa fa-envelope fa-2x"></i>
                        <p style="font-family:Sahel-Bold" class="h3 font-weight-normal mt-3">amingit2022@gmail.com</p>
                    </div>
                    <div class="col-4">
                        <i class="fa fa-map-marker fa-2x"></i>
                        <p style="font-family:Sahel-Bold" class="h3 font-weight-normal mt-3">تهران-شهران شمالی</p>
                    </div>
                    <div class="col-4">
                        <i class="fa fa-phone fa-2x"></i>
                        <p style="font-family:Sahel-Bold" class="h3 font-weight-normal mt-3">09037089794</p>
                    </div>
                  </div>

              </div>
            </div>
          </div>
          </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center" style="font-family:Sahel-Bold; width:100%; margin-right:1px">دسته بندی: {{category.title}}</h3>
{% endblock %}

{% block previous_page_url %}
   {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
   {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load base_tags %}
{% block main %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <span class="subheading"></span>
        </div>
      </div>
    </div>
    </div>
  </header>

<!-- Main Content-->
   <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            
            {% block header %}{% endblock %}
            {% for article in object_list %}
               <!-- Post preview-->
                <div class="post-preview" style="background-image: url('{% static "blog/assets/img/mountain2.jpg" %}')">
                 <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">
                      <span>
                        <svg class="SVG" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" width="14px" height="14px" viewBox="0 0 352.62 352.62" xml:space="preserve">
                          <g>
                            <path d="M337.222,22.952c-15.912-8.568-33.66,7.956-44.064,17.748c-23.867,23.256-44.063,50.184-66.708,74.664   c-25.092,26.928-48.348,53.856-74.052,80.173c-14.688,14.688-30.6,30.6-40.392,48.96c-22.032-21.421-41.004-44.677-65.484-63.648   c-17.748-13.464-47.124-23.256-46.512,9.18c1.224,42.229,38.556,87.517,66.096,116.28c11.628,12.24,26.928,25.092,44.676,25.704   c21.42,1.224,43.452-24.48,56.304-38.556c22.645-24.48,41.005-52.021,61.812-77.112c26.928-33.048,54.468-65.485,80.784-99.145   C326.206,96.392,378.226,44.983,337.222,22.952z M26.937,187.581c-0.612,0-1.224,0-2.448,0.611   c-2.448-0.611-4.284-1.224-6.732-2.448l0,0C19.593,184.52,22.653,185.132,26.937,187.581z" fill="#ce0005"></path>
                          </g>
                        </svg>
                      </span>
                      {{article.title}}
                      {% if article.is_special %} 
                      <span class="badge bg-danger"style="font-size:16px">ویژه</span>
                      {% endif %}
                    </h2>
                    <h3 class="post-subtitle">{{article.description | striptags | truncatewords:80}}</h3>
                 </a>
                 <p class="post-meta text-dark" style="text-shadow:1px 3px 2px #4e4e6d">
                     نوشته شده توسط
                     <a href="{% url 'blog:author' article.author %}" style="color:#3f3f61">{{article.author.get_full_name}}</a>
                    {{article.jpublish}}
                 <div>
                   {% for cat in article.category.active %}
                     <a href="{% url 'blog:category' cat.slug %}" style="color:#2b2b38; font-family:Sahel-Bold; text-shadow:1px 3px 2px #4e4e6d">دسته بندی: #{{cat.title}}</a>
                   {% endfor %}
                 </div>
                 </p>
                 <div style="font-family:Sahel-Bold; text-shadow:1px 3px 2px #4e4e6d"> بازدیدها:{{article.hits.count}}</div> 
             </div>
             <!-- Divider-->
             {% empty %}
                <div class="alert alert-danger" style="width:100%; margin-right: 2px">
                      متاسفانه محتوایی برای نمایش وجود ندارد...
                </div>
            {% endfor %}
              <!-- Pager-->
              {% if is_paginated %}
              <div class="clearfix pager-botton">
               {% if page_obj.has_previous %}
                 <a class="btn btn-primary float-right ml-3" style="font-family: 'Sahel-Bold';" href="{% block previous_page_url %}{% endblock %}">مقاله های جدید &rarr;</a>
               {% endif %}
               {% if page_obj.has_next %}
               <a class="btn btn-primary float-right" style="font-family: 'Sahel-Bold';" href="{% block next_page_url %}{% endblock %}">مقاله های قدیمی &larr;</a>
               {% endif %}
              </div>
            {% endif %}
          </div>
      </div>
  </div>
  
{% endblock %}

templates/blog/search_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="search alert alert-primary text-center">جستجو: {{search}}</h3>
{% endblock %}

{% block previous_page_url %}
   {% url 'blog:search' page_obj.previous_page_number %}?q={{search}}
{% endblock %}

{% block next_page_url %}
   {% url 'blog:search' page_obj.next_page_number %}?q={{search}}
{% endblock %}